export const COPY = {
  nav: {
    home: { fi: "Etusivu", en: "Home" },
    products: { fi: "Tuotteet", en: "Products" },
    story: { fi: "Tarina", en: "Story" },
    storyLong: { fi: "Tarinamme", en: "Our story" },
    order: { fi: "Tilaa", en: "Order" },
    contact: { fi: "Ota yhteyttä", en: "Contact" },
    lang: { fi: "Vaihda kieli, EN", en: "Switch language, FI" },
    mute: { fi: "Mykistä äänet", en: "Mute sounds" },
    unmute: { fi: "Poista mykistys", en: "Unmute sounds" },
    skip: { fi: "Siirry sisältöön", en: "Skip to content" },
  },
  footer: {
    tag: { fi: "Käsintehtyjä kynttilöitä", en: "Handmade candles" },
    blurb: {
      fi: "Jokainen LEIMU-kynttilä on pieneräinen käsityö, valmistettu 100% soijavahasta ja sheabutterista Suomessa.",
      en: "Every LEIMU candle is a small-batch craft, made from 100% soy wax and shea butter in Finland.",
    },
    nav: { fi: "Navigaatio", en: "Navigation" },
    contact: { fi: "Yhteystiedot", en: "Contact" },
    privacy: { fi: "Tietosuojaseloste", en: "Privacy policy" },
    rights: { fi: "Kaikki oikeudet pidätetään.", en: "All rights reserved." },
  },
  scent: {
    learn: { fi: "Lue lisää", en: "Learn more" },
    choose: { fi: "Valitse tuoksu", en: "Choose scent" },
    order: { fi: "Tilaa tämä tuoksu", en: "Order this scent" },
    close: { fi: "Sulje", en: "Close" },
    region: { fi: "Tuoksuvalikoima", en: "Scent collection" },
    prev: { fi: "Edellinen tuoksu", en: "Previous scent" },
    next: { fi: "Seuraava tuoksu", en: "Next scent" },
  },
  cart: {
    empty: { fi: "Kori on tyhjä", en: "Cart is empty" },
    bar: { fi: "Kori", en: "Cart" },
    continue: { fi: "Jatka", en: "Continue" },
    proceed: { fi: "Jatka tilaukseen", en: "Proceed to checkout" },
    add: { fi: "+ Lisää koriin", en: "+ Add to cart" },
    candles: { fi: "kynttilää", en: "candles" },
    pcs: { fi: "kpl", en: "pcs" },
    total: { fi: "Yhteensä", en: "Total" },
    rule: {
      fi: "Yksi rivi = yksi purkin väri. Enintään 6 kynttilää per rivi. Toinen väri lisätään uutena rivinä.",
      en: "One line = one jar colour. Max 6 candles per line. Add another colour as a new line.",
    },
  },
  checkout: {
    steps: {
      cart: { fi: "Ostoskori", en: "Cart" },
      details: { fi: "Yhteystiedot", en: "Details" },
      summary: { fi: "Yhteenveto", en: "Summary" },
    },
    back: { fi: "Takaisin", en: "Back" },
    next: { fi: "Seuraava", en: "Next" },
    firstName: { fi: "Etunimi", en: "First name" },
    lastName: { fi: "Sukunimi", en: "Last name" },
    email: { fi: "Sähköposti", en: "Email" },
    address: { fi: "Osoite", en: "Address" },
    zip: { fi: "Postinumero", en: "Postcode" },
    city: { fi: "Kaupunki", en: "City" },
    emailError: { fi: "Tarkista sähköpostiosoite.", en: "Check your email address." },
    heading: { fi: "Toimitus ja tiedot", en: "Delivery and details" },
    headingAccent: { fi: "tiedot", en: "details" },
    pickup: { fi: "Nouto Oulu", en: "Pickup in Oulu" },
    pickupHint: {
      fi: "Nouto Oulussa. Tarkka paikka vahvistetaan tilauksen jälkeen.",
      en: "Pickup in Oulu. The exact place is confirmed after the order.",
    },
    post: { fi: "Postitus +8€", en: "Postage +€8" },
    postHint: { fi: "Toimitus postitse Suomessa.", en: "Posted within Finland." },
    messageOpt: {
      fi: "Haluan käsinkirjoitetun viestin sinetöityyn kuoreen",
      en: "I want a handwritten message in the sealed envelope",
    },
    messageHint: {
      fi: "Kortti ja vahasinetti kuuluvat jokaiseen tilaukseen. Jos jätät viestin tyhjäksi, Shane kirjoittaa lyhyen oletustekstin.",
      en: "The card and wax seal come with every order. If you leave the message empty, Shane writes a short default.",
    },
    messageLabel: { fi: "Kirjoita viestisi", en: "Write your message" },
    messageHelp: {
      fi: "Erottele viestit numeroilla, esim: 1. Hyvää syntymäpäivää! 2. Rakastan sinua...",
      en: "Number separate notes, e.g. 1. Happy birthday! 2. I love you...",
    },
    privacy: {
      fi: "Olen lukenut ja hyväksyn, että tiedot käsitellään tietosuojaselosteen mukaisesti",
      en: "I have read and accept that details are handled per the privacy policy",
    },
    privacyLink: { fi: "tietosuojaselosteen", en: "privacy policy" },
    confirm: { fi: "Vahvista tilaus", en: "Confirm order" },
    processing: { fi: "Käsitellään…", en: "Processing…" },
    submitFail: {
      fi: "Tilauksen lähetys epäonnistui, tarkista yhteys ja yritä uudelleen.",
      en: "The order could not be sent. Check your connection and try again.",
    },
    code: { fi: "Alekoodi", en: "Discount code" },
    apply: { fi: "Käytä", en: "Apply" },
    codeBad: { fi: "Virheellinen koodi", en: "Invalid code" },
    discount: { fi: "Alennus", en: "Discount" },
    delivery: { fi: "Toimitus", en: "Delivery" },
    payment: { fi: "Maksutapa", en: "Payment" },
    paymentNeed: { fi: "Valitse maksutapa.", en: "Choose a payment method." },
    mobilepay: { fi: "MobilePay", en: "MobilePay" },
    siirto: { fi: "Siirto", en: "Siirto" },
    cash: { fi: "Käteinen noudettaessa", en: "Cash on pickup" },
    payHint: {
      fi: "Mainitse maksussa oma nimesi, jotta voimme yhdistää sen tilaukseesi.",
      en: "Put your name on the payment so we can match it to the order.",
    },
    review: { fi: "Tarkista tilauksesi ennen vahvistusta", en: "Review before confirming" },
    thanksTitle: { fi: "Kiitos tilauksestasi", en: "Thank you for your order" },
    thanksBody: {
      fi: "Tilaus vastaanotettu. Maksuohjeet alla. Emme lähetä erillistä kuittia tältä sivustolta.",
      en: "Order received. Payment details are below. This site does not send a separate receipt.",
    },
    newOrder: { fi: "Tee uusi tilaus", en: "Place another order" },
    contents: { fi: "Tilauksesi sisältö", en: "Your order" },
    payNow: { fi: "Maksa nyt, sitten valmistamme.", en: "Pay now, then we make it." },
  },
  contact: {
    title: { fi: "Yhteydenottopyyntö", en: "Contact request" },
    name: { fi: "Nimi", en: "Name" },
    email: { fi: "Sähköposti", en: "Email" },
    subject: { fi: "Mitä asia koskee?", en: "What is this about?" },
    subjectPh: { fi: "Esim. tilaus, yhteistyö, kysymys...", en: "e.g. order, collab, a question..." },
    message: { fi: "Kerro tarkemmin", en: "Tell us more" },
    send: { fi: "Lähetä", en: "Send" },
    sending: { fi: "Lähetetään…", en: "Sending…" },
    thanks: { fi: "Kiitos yhteydenotosta!", en: "Thanks for getting in touch!" },
    thanksBody: {
      fi: "Käsittelemme viestisi ja olemme sinuun yhteydessä tarvittaessa. Kiitos!",
      en: "We will read your message and reply if needed. Thank you!",
    },
    fail: {
      fi: "Viestin lähetys epäonnistui, tarkista yhteys ja yritä uudelleen.",
      en: "The message could not be sent. Check your connection and try again.",
    },
  },
  notFound: {
    title: { fi: "Tätä sivua ei löytynyt.", en: "This page was not found." },
    body: {
      fi: "Sivu on voitu siirtää tai poistaa. Tarkista osoite tai palaa etusivulle.",
      en: "The page may have moved or been removed. Check the address or return home.",
    },
    home: { fi: "Takaisin etusivulle", en: "Back to home" },
  },
  privacy: {
    doc: { fi: "Asiakirja", en: "Document" },
    title: { fi: "Tietosuojaseloste", en: "Privacy policy" },
  },
} as const;

export type Lang = "fi" | "en";
